### ISSUE TITLE
How do I specify the side(s) (top, right, bottom, left) of elements to draw from/to?

### ISSUE THREAD

**Issue by nomorechickennuggets** [musclesoft/jquery-connections#16]
Is there any way to specify that I only want to draw lines from the left side of my div to the right side of another div?

The effect I'm going for:

![image](https://user-images.githubusercontent.com/9064528/52504978-fa8ecb00-2b9e-11e9-8558-43c071fc2cc0.png)

**Comment by diamond-msc** [comment]
Hey @sb2059, the plugin currently supports only L-shaped connections.
That said, in order to get an S-shaped connection, you need an invisible anchor, a third element positioned at the center of the S.
Maybe have a look at the test card 
https://musclesoft.github.io/jquery-connections/demo/testmatrix.html and check out the “s plumbing anchor”.
