### ISSUE TITLE
Lines loosing uniformity

### ISSUE THREAD

**Issue by alok15ee** [musclesoft/jquery-connections#8]
I am facing this issue and all the details with screenshots are here
http://stackoverflow.com/questions/31410691/connecting-lines-loosing-uniformity-when-number-of-elements-on-webpage-is-increa
Please have a look into this.

**Comment by diamond-msc** [comment]
Hey @alok15ee,

I've set up a fiddle from your description: http://jsfiddle.net/yt26wq8t/1/

Could you please provide some more details to reproduce the issue?
- Which browsers did you test with?
- What jQuery version are you using?
- It would be perfect if you'd be able to update the fiddle, to make it reproduce the issue

Maybe the issue is related to http://stackoverflow.com/questions/6032429/chrome-timeouts-interval-suspended-in-background-tabs

**Comment by alok15ee** [comment]
Hi David,

Thanks for replying back. The issue was happening because of the
integration I was trying with one of the framework I was using called AJS.
It was not properly loading the connection due to the time lag set.

Thanks Again.

Thanks and regards,
_Alok Kumar Singh_
Co-Founder and Tools Specialist @ Leanpitch
Bangalore
Ph: 9538978866 | skype: alok15ee
