### ISSUE TITLE
anchor position at center by default

### ISSUE THREAD

**Issue by hasanhameed07** [musclesoft/jquery-connections#9]
Hi, Can you brief if there is a way to set anchor point for the connection like left,right,top or bottom? It is always creating center anchor for the source element which I don't want in my case.

**Comment by diamond-msc** [comment]
Hi @hasanhameed07,

Forcing an anchor position is not supported by default.

However, depending on what exactly you want to achieve, you may be able to control anchor positions:

Instead of connecting your elements directly, connect nested anchor elements.
Since the anchor elements are fully under your control, positioning them should be easy.
(However, the slope direction calculation may be suboptimal with this approach, YMMV)

Example fiddle: http://jsfiddle.net/FP7Zy/180/

**Comment by hasanhameed07** [comment]
Well thanx for this approach! Hope this will be added in the library soon.
